### ISSUE TITLE
输入docker-compose up -d 以后报错

### ISSUE THREAD

**Issue by svgr110** [elecV2/elecV2P#126]
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/bin/docker-compose", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: docker-compose

**Comment by elecV2** [comment]
搜索: PackageNotFoundError: docker-compose

PS: 如果基础安装问题不能通过说明文档或搜索解决，建议还是放弃比较好，不然之后还会浪费更多时间，不值得。
