### ISSUE TITLE
我是小白，还是没法看懂如何运行elecV2P

### ISSUE THREAD

**Issue by MJ0420** [elecV2/elecV2P#170]
我感觉真的要下载好多东西 首先我下载了git，下载了nodejs，下载了yarn
搞完了跟着步骤安装后，我发现我不会打开那个控制面板 
也不知道是不是要修改index.js or config.js 的文件
我也不知道怎么样查看服务器地址QAQ 有没有大佬出个视频教一教

yarn install v1.22.19>yarn
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.21s.

yarn run v1.22.19cV2P>yarn start
$ pm2 start index.js -n elecV2P -o logs/pm2.log -e logs/pm2-error.log --no-daemon
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
[PM2][ERROR] Script already launched, add -f option to force re-execution
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\User\elecV2P>node index.js
[utilsFile   info][2022-07-25 00:57:20.162] elecV2P start 10 times
[funcTask    info][2022-07-25 00:57:20.249] retrieve task from Lists/task.list
[funcTask    info][2022-07-25 00:57:20.250] no autoupdate for sub task: elecV2P 任务订阅
[elecV2P   notify][2022-07-25 00:57:20.255] default rules: disabled
[elecV2P   notify][2022-07-25 00:57:20.255] rewrite rules: 1
[elecV2P   notify][2022-07-25 00:57:20.256] MITM hosts: 2
[webSocket notify][2022-07-25 00:57:20.271] websocket on path: /elecV2P
[elecV2P     info][2022-07-25 00:57:20.271] anyproxy not enabled yet
[webSocket  error][2022-07-25 00:57:20.274] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[logger      info][2022-07-25 00:57:20.279] total amount of logs: 6 total size: 23.74 K
elecV2P exited.

**Comment by MJ0420** [comment]
我是从这里过来的https://github.com/Oreomeow/checkinpanel 还是说我可以直接用这个checkinpanel启动 elecV2P

**Comment by elecV2** [comment]
仔细看看项目 Readme.md 的说明吧。记得先 yarn 安装依赖。
其他我也没办法更详细的说明了

**Comment by MJ0420** [comment]
> 仔细看看项目 Readme.md 的说明吧。记得先 yarn 安装依赖。 其他我也没办法更详细的说明了

C:\Users\User\elecV2P>yarn
yarn install v1.22.19
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning anyproxy > clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
warning anyproxy > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning anyproxy > request > har-validator@5.1.5: this library is no longer supported
warning anyproxy > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning anyproxy > pug > pug-code-gen > constantinople > babel-types > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning pm2 > @pm2/io > @opencensus/core > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning pm2 > @pm2/io > @opencensus/propagation-b3 > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning pm2 > @pm2/io > @opencensus/propagation-b3 > @opencensus/core > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "anyproxy > svg-inline-react@1.0.3" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 12.36s.

C:\Users\User\elecV2P>yarn global add pm2
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "pm2@5.2.0" with binaries:
      - pm2
      - pm2-dev
      - pm2-docker
      - pm2-runtime
Done in 1.33s.

C:\Users\User\elecV2P>yarn start
yarn run v1.22.19
$ pm2 start index.js -n elecV2P -o logs/pm2.log -e logs/pm2-error.log --no-daemon
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2022-07-25T14:31:16: PM2 log: Launching in no daemon mode
2022-07-25T14:31:16: PM2 log: [PM2] Starting C:\Users\User\elecV2P\index.js in fork_mode (1 instance)
2022-07-25T14:31:16: PM2 log: App [elecV2P:0] starting in -fork mode-
2022-07-25T14:31:16: PM2 log: App [elecV2P:0] online
2022-07-25T14:31:16: PM2 log: [PM2] Done.
2022-07-25T14:31:17: PM2 log: ┌─────┬────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name       │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ elecV2P    │ default     │ 3.6.8   │ fork    │ 1752     │ 0s     │ 0    │ online    │ 4.7%     │ 27.3mb   │ User     │ disabled │
└─────┴────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
2022-07-25T14:31:17: PM2 log: [PM2][WARN] Current process list is not synchronized with saved list. Type 'pm2 save' to synchronize.
2022-07-25T14:31:17: PM2 log: [--no-daemon] Continue to stream logs
2022-07-25T14:31:17: PM2 log: [--no-daemon] Exit on target PM2 exit pid=9476
14:31:25 0|elecV2P  | [utilsFile   info][2022-07-25 14:31:25.233] elecV2P start 11 times
14:31:26 0|elecV2P  | [funcTask    info][2022-07-25 14:31:26.027] retrieve task from Lists/task.list
14:31:26 0|elecV2P  | [funcTask    info][2022-07-25 14:31:26.028] no autoupdate for sub task: elecV2P 任务订阅
14:31:26 0|elecV2P  | [elecV2P   notify][2022-07-25 14:31:26.069] default rules: disabled
14:31:26 0|elecV2P  | [elecV2P   notify][2022-07-25 14:31:26.069] rewrite rules: 1
14:31:26 0|elecV2P  | [elecV2P   notify][2022-07-25 14:31:26.069] MITM hosts: 2
14:31:26 0|elecV2P  | [webSocket notify][2022-07-25 14:31:26.152] websocket on path: /elecV2P
14:31:26 0|elecV2P  | [elecV2P     info][2022-07-25 14:31:26.152] anyproxy not enabled yet
14:31:26 0|elecV2P  | [webServer notify][2022-07-25 14:31:26.153] elecV2P v3.6.8 started on port 80
14:31:26 0|elecV2P  | [logger      info][2022-07-25 14:31:26.156] total amount of logs: 6 total size: 25.42 K

这个就是我跟着readme.md 的步骤做的具体哪里有问题呢

**Comment by elecV2** [comment]
看起来没什么问题。找到 logs目录下的 errrors.log 看有什么提醒

**Comment by MJ0420** [comment]
[webSocket  error][2022-07-25 00:05:38.723] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[webSocket  error][2022-07-25 00:07:56.647] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[webSocket  error][2022-07-25 00:30:09.690] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[webSocket  error][2022-07-25 00:39:44.822] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[webSocket  error][2022-07-25 00:47:01.104] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[webSocket  error][2022-07-25 00:47:49.951] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[webSocket  error][2022-07-25 00:48:01.092] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[webSocket  error][2022-07-25 00:57:20.274] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
[webSocket  error][2022-07-25 14:33:42.022] websocket error Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}


> 看起来没什么问题。找到 logs目录下的 errrors.log 看有什么提醒

**Comment by elecV2** [comment]
80端口已占用。再看看readme 里的说明吧

**Comment by MJ0420** [comment]
是这样吗

C:\Users\User\elecV2P>set PORT=8000 node index.js

C:\Users\User\elecV2P>node index.js
[utilsFile   info][2022-07-25 15:24:09.987] elecV2P start 14 times
[funcTask    info][2022-07-25 15:24:10.074] retrieve task from Lists/task.list
[funcTask    info][2022-07-25 15:24:10.075] no autoupdate for sub task: elecV2P 任务订阅
[elecV2P   notify][2022-07-25 15:24:10.081] default rules: disabled
[elecV2P   notify][2022-07-25 15:24:10.081] rewrite rules: 1
[elecV2P   notify][2022-07-25 15:24:10.081] MITM hosts: 2
[webSocket notify][2022-07-25 15:24:10.098] websocket on path: /elecV2P
[elecV2P     info][2022-07-25 15:24:10.098] anyproxy not enabled yet
[webSocket  error][2022-07-25 15:24:10.101] websocket error Error: listen EACCES: permission denied 8000 node index.js
    at Server.setupListenHandle [as _listen2] (node:net:1355:21)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1519:5)
    at module.exports (C:\Users\User\elecV2P\webmodule.js:59:10)
    at Object.<anonymous> (C:\Users\User\elecV2P\index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '8000 node index.js',
  port: -1
}
[logger      info][2022-07-25 15:24:10.104] total amount of logs: 6 total size: 26.88 K
elecV2P exited.

> 80端口已占用。再看看readme 里的说明吧

**Comment by elecV2** [comment]
学会简单的看看日志，和 google 等搜索工具，比如：error][2022-07-25 15:24:10.101] websocket error Error: listen EACCES: permission denied 8000
