### ISSUE TITLE
TypeError: Cannot read property 'code' of undefined 

### ISSUE THREAD

**Issue by ktownag** [elecV2/elecV2P#2]
运行脚本 https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Task/jd_fruit.js 时报错：
TypeError: Cannot read property 'code' of undefined 
    at step (evalmachine.<anonymous>:252:43)
    at step.next (<anonymous>)
    at Timeout._onTimeout (evalmachine.<anonymous>:596:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ktownag** [comment]
![image](https://user-images.githubusercontent.com/42381296/86638444-5b1a7580-bfe8-11ea-9ac0-3bf529d5830c.png)

**Comment by elecV2** [comment]
已记录，这边暂时无法解决。如果要用的话可能需要手动修改一下脚本。
