### ISSUE TITLE
VERSION: 3.3.8 在termux上启动失败，有遇到同样问题的朋友吗？

### ISSUE THREAD

**Issue by EchoChan314** [elecV2/elecV2P#86]
2021-05-28T19:52:43: PM2 log: [PM2] Starting /data/data/com.termux/files/home/elecV2P/index.js in fork_mode (1 instance)
2021-05-28T19:52:43: PM2 log: App [elecV2P:0] starting in -fork mode-
2021-05-28T19:52:43: PM2 log: App [elecV2P:0] online
2021-05-28T19:52:43: PM2 log: [PM2] Done.
2021-05-28T19:52:43: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-05-28T19:52:43: PM2 error: Error while getting CLK_TCK Error: Command failed: getconf CLK_TCK
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 127,
  signal

之前只试过3.3.7，当时可以运行，但是我只是搭建了，可以进入后台，但没继续玩，这个重新下载3.3.8，重新安装依赖，却发现运行不起来，好奇怪。

**Comment by elecV2** [comment]
如果 3.3.7 没问题，3.3.8 应该也不会有什么问题。重装试试吧（包括 termux

**Comment by EchoChan314** [comment]
@elecV2 嗯，知道原因了，就是getconf没装，但是我之前运行3.3.7的时候也是没装过getconf的，但却可以运行起来。奇怪。
